# frozen_string_literal: true

# Generates lib/teams/cards/generated.rb from script/cards_ir.json, which is
# produced by script/extract_cards_ir.py from the teams.py generated Pydantic
# card models. Regeneration flow after an upstream pull:
#
#   cd ../teams.py && uv run python ../teams_rb/script/extract_cards_ir.py
#   ruby script/generate_cards.rb
#   bundle exec rake test

require "json"

ir_path = File.expand_path("cards_ir.json", __dir__)
out_path = File.expand_path("../lib/teams/cards/generated.rb", __dir__)

ir = JSON.parse(File.read(ir_path))

# Ruby conveniences preserved from the original hand-written classes.
POSITIONAL = {
  "TextBlock" => :text,
  "OpenUrlAction" => :url
}.freeze

SPLAT = {
  "AdaptiveCard" => :body,
  "ActionSet" => :actions,
  "ChoiceSetInput" => :choices
}.freeze

ADDERS = {
  "AdaptiveCard" => { add_item: :body, add_action: :actions },
  "ActionSet" => { add_action: :actions },
  "ChoiceSetInput" => { add_choice: :choices }
}.freeze

RESERVED = %w[initialize to_h to_json].freeze

def ruby_literal(value)
  value.inspect
end

lines = []
lines << "# frozen_string_literal: true"
lines << ""
lines << "# Generated by script/generate_cards.rb from script/cards_ir.json."
lines << "# DO NOT EDIT MANUALLY - regenerate after upstream teams.py updates."
lines << ""
lines << "module Teams"
lines << "  module Cards"

ir.fetch("classes").each do |klass|
  name = klass.fetch("name")
  parent = klass["parent"] || "GeneratedCard"
  doc = klass["doc"].to_s.strip

  lines << ""
  lines << "    # #{doc}" unless doc.empty?
  lines << "    class #{name} < #{parent}"

  own_fields = klass.fetch("fields").select { |field| field["own"] }
  own_fields.each do |field|
    field_name = field.fetch("name")
    raise "field #{name}##{field_name} collides with a reserved method" if RESERVED.include?(field_name)

    args = [":#{field_name}", field.fetch("alias").inspect]
    args << ruby_literal(field["default"]) unless field["default"].nil?
    keyword = field["mutable"] ? ", mutable: true" : ""
    lines << "      field #{args.join(', ')}#{keyword}"
  end

  lines << "      positional_field :#{POSITIONAL[name]}" if POSITIONAL.key?(name)
  lines << "      splat_field :#{SPLAT[name]}" if SPLAT.key?(name)
  ADDERS.fetch(name, {}).each do |method_name, field_name|
    lines << "      array_adder :#{method_name}, :#{field_name}"
  end

  lines << "    end"
end

lines << "  end"
lines << "end"
lines << ""

File.write(out_path, lines.join("\n"))
puts "wrote #{out_path} (#{lines.length} lines, #{ir.fetch('classes').length} classes)"
