# frozen_string_literal: true

# Generated by script/generate_cards.rb from script/cards_ir.json.
# DO NOT EDIT MANUALLY - regenerate after upstream teams.py updates.

module Teams
  module Cards

    # Base class for all serializable objects.
    class SerializableObject < GeneratedCard
    end

    # Base class for Action.
    class Action < SerializableObject
    end

    # Defines a button as displayed when prompting a user to authenticate. For more information, refer to the [Bot Framework CardAction type](https://docs.microsoft.com/dotnet/api/microsoft.bot.schema.cardaction).
    class AuthCardButton < SerializableObject
      field :key, "key"
      field :type, "type"
      field :title, "title"
      field :image, "image"
      field :value, "value"
    end

    # Defines authentication information associated with a card. For more information, refer to the [Bot Framework OAuthCard type](https://docs.microsoft.com/dotnet/api/microsoft.bot.schema.oauthcard)
    class Authentication < SerializableObject
      field :key, "key"
      field :text, "text"
      field :connection_name, "connectionName"
      field :buttons, "buttons"
      field :token_exchange_resource, "tokenExchangeResource"
    end

    # Defines a container's background image and the way it should be rendered.
    class BackgroundImage < SerializableObject
      field :key, "key"
      field :url, "url"
      field :fill_mode, "fillMode", "Cover"
      field :horizontal_alignment, "horizontalAlignment", "Left"
      field :vertical_alignment, "verticalAlignment", "Top"
      field :themed_urls, "themedUrls"
    end

    # A single data point in a bar chart.
    class BarChartDataValue < SerializableObject
      field :key, "key"
      field :x, "x"
      field :y, "y", 0
    end

    # Represents a calendar event attendee.
    class CalendarEventAttendee < SerializableObject
      field :key, "key"
      field :name, "name"
      field :email, "email"
      field :title, "title"
      field :type, "type"
      field :status, "status"
    end

    # The properties of a calendar event.
    class CalendarEventProperties < SerializableObject
      field :key, "key"
      field :id, "id"
      field :title, "title"
      field :start, "start"
      field :end, "end"
      field :status, "status"
      field :locations, "locations"
      field :online_meeting_url, "onlineMeetingUrl"
      field :is_all_day, "isAllDay"
      field :extension, "extension"
      field :url, "url"
      field :attendees, "attendees"
      field :organizer, "organizer"
    end

    # Defines a source URL for a video captions.
    class CaptionSource < SerializableObject
      field :key, "key"
      field :mime_type, "mimeType"
      field :url, "url"
      field :label, "label"
    end

    # Base class for CardElement.
    class CardElement < SerializableObject
    end

    # Card-level metadata.
    class CardMetadata < SerializableObject
      field :key, "key"
      field :web_url, "webUrl"
    end

    # A choice as used by the Input.ChoiceSet input.
    class Choice < SerializableObject
      field :key, "key"
      field :title, "title"
      field :value, "value"
    end

    # Data for invoking a collaboration stage action.
    class CollabStageInvokeDataValue < SerializableObject
      field :type, "type", "tab/tabInfoAction"
      field :tab_info, "tabInfo"
    end

    # Defines a column in a Table element.
    class ColumnDefinition < SerializableObject
      field :key, "key"
      field :horizontal_cell_content_alignment, "horizontalCellContentAlignment"
      field :vertical_cell_content_alignment, "verticalCellContentAlignment"
      field :width, "width"
    end

    # Base class for ContainerLayout.
    class ContainerLayout < SerializableObject
    end

    # A data point in a Donut chart.
    class DonutChartData < SerializableObject
      field :key, "key"
      field :legend, "legend"
      field :value, "value", 0
      field :color, "color"
    end

    # A fact in a FactSet element.
    class Fact < SerializableObject
      field :key, "key"
      field :title, "title"
      field :value, "value"
    end

    # Represents the properties of a file component.
    class FileProperties < SerializableObject
      field :key, "key"
      field :name, "name"
      field :extension, "extension"
      field :url, "url"
    end

    # The legend of the chart.
    class GaugeChartLegend < SerializableObject
      field :key, "key"
      field :size, "size", 0
      field :legend, "legend"
      field :color, "color"
    end

    # Defines an area in a Layout.AreaGrid layout.
    class GridArea < SerializableObject
      field :key, "key"
      field :name, "name"
      field :column, "column", 1
      field :column_span, "columnSpan", 1
      field :row, "row", 1
      field :row_span, "rowSpan", 1
    end

    # Represents a series of data points.
    class GroupedVerticalBarChartData < SerializableObject
      field :key, "key"
      field :legend, "legend"
      field :values, "values"
      field :color, "color"
    end

    # Represents a single data point in a horizontal bar chart.
    class HorizontalBarChartDataValue < SerializableObject
      field :key, "key"
      field :x, "x"
      field :y, "y", 0
      field :color, "color"
    end

    # Represents a list of versioned capabilities a host application must support.
    class HostCapabilities < SerializableObject
      field :key, "key"
    end

    # Defines information about a Fluent icon and how it should be rendered.
    class IconInfo < SerializableObject
      field :key, "key"
      field :name, "name"
      field :size, "size", "xSmall"
      field :style, "style", "Regular"
      field :color, "color", "Default"
    end

    # Represents Teams-specific data in an Action.Submit to send an Instant Message back to the Bot.
    class ImBackSubmitActionData < SerializableObject
      field :key, "key"
      field :type, "type", "imBack"
      field :value, "value"
    end

    # Represents Teams-specific data in an Action.Submit to make an Invoke request to the Bot.
    class InvokeSubmitActionData < SerializableObject
      field :key, "key"
      field :type, "type", "invoke"
      field :value, "value"
    end

    # Represents a collection of data points series in a line chart.
    class LineChartData < SerializableObject
      field :key, "key"
      field :legend, "legend"
      field :values, "values"
      field :color, "color"
    end

    # Represents a single data point in a line chart.
    class LineChartValue < SerializableObject
      field :key, "key"
      field :x, "x"
      field :y, "y", 0
    end

    # Defines the source URL of a media stream. YouTube, Dailymotion, Vimeo and Microsoft Stream URLs are supported.
    class MediaSource < SerializableObject
      field :key, "key"
      field :mime_type, "mimeType"
      field :url, "url"
    end

    # Represents a mention to a person.
    class Mention < SerializableObject
      field :key, "key"
      field :type, "type", "mention"
      field :text, "text"
      field :mentioned, "mentioned"
    end

    # Represents a mentioned person or tag.
    class MentionedEntity < SerializableObject
      field :key, "key"
      field :id, "id"
      field :name, "name"
      field :mention_type, "mentionType", "Person"
    end

    # Represents Teams-specific data in an Action.Submit to send a message back to the Bot.
    class MessageBackSubmitActionData < SerializableObject
      field :key, "key"
      field :type, "type", "messageBack"
      field :text, "text"
      field :display_text, "displayText"
      field :value, "value"
    end

    # Represents the properties of a Persona component.
    class PersonaProperties < SerializableObject
      field :key, "key"
      field :id, "id"
      field :user_principal_name, "userPrincipalName"
      field :display_name, "displayName"
      field :icon_style, "iconStyle"
      field :style, "style"
    end

    # Represents the properties of a PersonaSet component.
    class PersonaSetProperties < SerializableObject
      field :key, "key"
      field :users, "users"
      field :icon_style, "iconStyle"
      field :style, "style"
    end

    # Defines a query to dynamically fetch data from a Bot.
    class QueryData < SerializableObject
      field :key, "key"
      field :type, "type", "Data.Query"
      field :dataset, "dataset"
      field :associated_inputs, "associatedInputs"
      field :count, "count"
      field :skip, "skip"
    end

    # Defines how a card can be refreshed by making a request to the target Bot.
    class RefreshDefinition < SerializableObject
      field :key, "key"
      field :action, "action"
      field :user_ids, "userIds"
    end

    # Represents the properties of a resource component.
    class ResourceProperties < SerializableObject
      field :key, "key"
      field :id, "id"
      field :resource_reference, "resourceReference"
      field :resource_visualization, "resourceVisualization"
    end

    # Represents a visualization of a resource.
    class ResourceVisualization < SerializableObject
      field :key, "key"
      field :media, "media"
    end

    # The resources that can be used in the body of the card.
    class Resources < SerializableObject
      field :key, "key"
      field :strings, "strings"
    end

    # Represents Teams-specific data in an Action.Submit to sign in a user.
    class SigninSubmitActionData < SerializableObject
      field :key, "key"
      field :type, "type", "signin"
      field :value, "value"
    end

    # Defines the collection of data series to display in as a stacked horizontal bar chart.
    class StackedHorizontalBarChartData < SerializableObject
      field :key, "key"
      field :title, "title"
      field :data, "data"
    end

    # A data point in a series.
    class StackedHorizontalBarChartDataPoint < SerializableObject
      field :key, "key"
      field :legend, "legend"
      field :value, "value", 0
      field :color, "color"
    end

    # Defines the replacement string values.
    class StringResource < SerializableObject
      field :key, "key"
      field :default_value, "defaultValue"
      field :localized_values, "localizedValues"
    end

    # Represents the data of an Action.Submit.
    class SubmitActionData < SerializableObject
      field :key, "key"
      field :msteams, "msteams"
    end

    # Represents information about the iFrame content, rendered in the collab stage popout window.
    class TabInfo < SerializableObject
      field :name, "name"
      field :content_url, "contentUrl"
      field :entity_id, "entityId"
      field :website_url, "websiteUrl"
    end

    # Defines a target element in an Action.ToggleVisibility.
    class TargetElement < SerializableObject
      field :element_id, "elementId"
      field :is_visible, "isVisible"
    end

    # Represents Teams-specific data in an Action.Submit to open a task module.
    class TaskFetchSubmitActionData < SerializableObject
      field :key, "key"
      field :type, "type", "task/fetch"
    end

    # Represents a set of Teams-specific properties on a card.
    class TeamsCardProperties < SerializableObject
      field :key, "key"
      field :width, "width"
      field :entities, "entities"
    end

    # Represents a set of Teams-specific properties on an image.
    class TeamsImageProperties < SerializableObject
      field :key, "key"
      field :allow_expand, "allowExpand"
    end

    # Represents feedback options for an [Action.Submit](https://adaptivecards.microsoft.com/?topic=Action.Submit).
    class TeamsSubmitActionFeedback < SerializableObject
      field :key, "key"
      field :hide, "hide"
    end

    # Teams-specific properties associated with the action.
    class TeamsSubmitActionProperties < SerializableObject
      field :key, "key"
      field :feedback, "feedback"
    end

    # Defines a theme-specific URL.
    class ThemedUrl < SerializableObject
      field :key, "key"
      field :theme, "theme", "Light"
      field :url, "url"
    end

    # Defines information required to enable on-behalf-of single sign-on user authentication. For more information, refer to the [Bot Framework TokenExchangeResource type](https://docs.microsoft.com/dotnet/api/microsoft.bot.schema.tokenexchangeresource)
    class TokenExchangeResource < SerializableObject
      field :key, "key"
      field :id, "id"
      field :uri, "uri"
      field :provider_id, "providerId"
    end

    # Represents a data point in a vertical bar chart.
    class VerticalBarChartDataValue < SerializableObject
      field :key, "key"
      field :x, "x"
      field :y, "y", 0
      field :color, "color"
    end

    # Displays a set of action, which can be placed anywhere in the card.
    class ActionSet < CardElement
      field :key, "key"
      field :type, "type", "ActionSet"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :actions, "actions"
      splat_field :actions
      array_adder :add_action, :actions
    end

    # An Adaptive Card, containing a free-form body of card elements, and an optional set of actions.
    class AdaptiveCard < CardElement
      field :key, "key"
      field :type, "type", "AdaptiveCard"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_sort_key, "isSortKey", false
      field :select_action, "selectAction"
      field :style, "style"
      field :layouts, "layouts"
      field :min_height, "minHeight"
      field :background_image, "backgroundImage"
      field :vertical_content_alignment, "verticalContentAlignment"
      field :rtl, "rtl"
      field :ac_schema, "schema"
      field :version, "version", "1.5"
      field :fallback_text, "fallbackText"
      field :speak, "speak"
      field :refresh, "refresh"
      field :authentication, "authentication"
      field :msteams, "msteams"
      field :metadata, "metadata"
      field :resources, "resources"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :body, "body"
      field :actions, "actions"
      splat_field :body
      array_adder :add_item, :body
      array_adder :add_action, :actions
    end

    # A layout that divides a container into named areas into which elements can be placed.
    class AreaGridLayout < ContainerLayout
      field :key, "key"
      field :type, "type", "Layout.AreaGrid"
      field :target_width, "targetWidth"
      field :columns, "columns"
      field :areas, "areas"
      field :column_spacing, "columnSpacing", "Default"
      field :row_spacing, "rowSpacing", "Default"
    end

    # A badge element to show an icon and/or text in a compact form over a colored background.
    class Badge < CardElement
      field :key, "key"
      field :type, "type", "Badge"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :text, "text"
      field :icon, "icon"
      field :icon_position, "iconPosition", "Before"
      field :appearance, "appearance", "Filled"
      field :size, "size", "Medium"
      field :shape, "shape", "Circular"
      field :style, "style", "Default"
      field :tooltip, "tooltip"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A carousel with sliding pages.
    class Carousel < CardElement
      field :key, "key"
      field :type, "type", "Carousel"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :bleed, "bleed", false
      field :min_height, "minHeight"
      field :page_animation, "pageAnimation", "Slide"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :pages, "pages"
    end

    # A page inside a Carousel element.
    class CarouselPage < CardElement
      field :key, "key"
      field :type, "type", "CarouselPage"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :height, "height", "auto"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :select_action, "selectAction"
      field :style, "style"
      field :show_border, "showBorder", false
      field :rounded_corners, "roundedCorners", false
      field :layouts, "layouts"
      field :min_height, "minHeight"
      field :background_image, "backgroundImage"
      field :vertical_content_alignment, "verticalContentAlignment"
      field :rtl, "rtl"
      field :max_height, "maxHeight"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :items, "items"
    end

    # An input to allow the user to select one or more values.
    class ChoiceSetInput < CardElement
      field :key, "key"
      field :type, "type", "Input.ChoiceSet"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value"
      field :choices, "choices"
      field :choices_data, "choices.data"
      field :style, "style", "compact"
      field :is_multi_select, "isMultiSelect", false
      field :placeholder, "placeholder"
      field :wrap, "wrap", true
      field :use_multiple_columns, "useMultipleColumns", false
      field :min_column_width, "minColumnWidth"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      splat_field :choices
      array_adder :add_choice, :choices
    end

    # A formatted and syntax-colored code block.
    class CodeBlock < CardElement
      field :key, "key"
      field :type, "type", "CodeBlock"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :code_snippet, "codeSnippet"
      field :language, "language", "PlainText"
      field :start_line_number, "startLineNumber", 1
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A column in a ColumnSet element.
    class Column < CardElement
      field :key, "key"
      field :type, "type", "Column"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :select_action, "selectAction"
      field :style, "style"
      field :show_border, "showBorder", false
      field :rounded_corners, "roundedCorners", false
      field :layouts, "layouts"
      field :bleed, "bleed", false
      field :min_height, "minHeight"
      field :background_image, "backgroundImage"
      field :vertical_content_alignment, "verticalContentAlignment"
      field :rtl, "rtl"
      field :max_height, "maxHeight"
      field :width, "width"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :items, "items"
    end

    # Splits the available horizontal space into separate columns, so elements can be organized in a row.
    class ColumnSet < CardElement
      field :key, "key"
      field :type, "type", "ColumnSet"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :select_action, "selectAction"
      field :style, "style"
      field :show_border, "showBorder", false
      field :rounded_corners, "roundedCorners", false
      field :bleed, "bleed", false
      field :min_height, "minHeight"
      field :min_width, "minWidth"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :columns, "columns"
    end

    # Displays information about a calendar event.
    class ComEventMicrosoftGraphComponent < CardElement
      field :key, "key"
      field :type, "type", "Component"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :name, "name", "graph.microsoft.com/event"
      field :properties, "properties"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Displays information about a file resource.
    class ComFileMicrosoftGraphComponent < CardElement
      field :key, "key"
      field :type, "type", "Component"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :name, "name", "graph.microsoft.com/file"
      field :properties, "properties"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Displays information about a generic graph resource.
    class ComResourceMicrosoftGraphComponent < CardElement
      field :key, "key"
      field :type, "type", "Component"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :name, "name", "graph.microsoft.com/resource"
      field :properties, "properties"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Displays a user's information, including their profile picture.
    class ComUserMicrosoftGraphComponent < CardElement
      field :key, "key"
      field :type, "type", "Component"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :name, "name", "graph.microsoft.com/user"
      field :properties, "properties"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Displays multiple users' information, including their profile pictures.
    class ComUsersMicrosoftGraphComponent < CardElement
      field :key, "key"
      field :type, "type", "Component"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :name, "name", "graph.microsoft.com/users"
      field :properties, "properties"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A special type of button with an icon, title and description.
    class CompoundButton < CardElement
      field :key, "key"
      field :type, "type", "CompoundButton"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :icon, "icon"
      field :badge, "badge"
      field :title, "title"
      field :description, "description"
      field :select_action, "selectAction"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A container for other elements. Use containers for styling purposes and/or to logically group a set of elements together, which can be especially useful when used with Action.ToggleVisibility.
    class Container < CardElement
      field :key, "key"
      field :type, "type", "Container"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :select_action, "selectAction"
      field :style, "style"
      field :show_border, "showBorder", false
      field :rounded_corners, "roundedCorners", false
      field :layouts, "layouts"
      field :bleed, "bleed", false
      field :min_height, "minHeight"
      field :background_image, "backgroundImage"
      field :vertical_content_alignment, "verticalContentAlignment"
      field :rtl, "rtl"
      field :max_height, "maxHeight"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :items, "items"
    end

    # An input to allow the user to select a date.
    class DateInput < CardElement
      field :key, "key"
      field :type, "type", "Input.Date"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value"
      field :placeholder, "placeholder"
      field :min, "min"
      field :max, "max"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A donut chart.
    class DonutChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.Donut"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :data, "data"
      field :value, "value"
      field :value_color, "valueColor"
      field :thickness, "thickness"
      field :show_outlines, "showOutlines", true
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Gathers input values, merges them with the data property if specified, and sends them to the Bot via an Invoke activity. The Bot can respond synchronously and return an updated Adaptive Card to be displayed by the client. Action.Execute works in all Adaptive Card hosts.
    class ExecuteAction < Action
      field :key, "key"
      field :type, "type", "Action.Execute"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :data, "data"
      field :associated_inputs, "associatedInputs"
      field :conditionally_enabled, "conditionallyEnabled", false
      field :verb, "verb"
      field :fallback, "fallback"
    end

    # A set of facts, displayed as a table or a vertical list when horizontal space is constrained.
    class FactSet < CardElement
      field :key, "key"
      field :type, "type", "FactSet"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :facts, "facts"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A layout that spreads elements horizontally and wraps them across multiple rows, as needed.
    class FlowLayout < ContainerLayout
      field :key, "key"
      field :type, "type", "Layout.Flow"
      field :target_width, "targetWidth"
      field :horizontal_items_alignment, "horizontalItemsAlignment", "Center"
      field :vertical_items_alignment, "verticalItemsAlignment", "Top"
      field :item_fit, "itemFit", "Fit"
      field :min_item_width, "minItemWidth"
      field :max_item_width, "maxItemWidth"
      field :item_width, "itemWidth"
      field :column_spacing, "columnSpacing", "Default"
      field :row_spacing, "rowSpacing", "Default"
    end

    # A gauge chart.
    class GaugeChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.Gauge"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :min, "min", 0
      field :max, "max"
      field :sub_label, "subLabel"
      field :show_min_max, "showMinMax", true
      field :show_needle, "showNeedle", true
      field :show_outlines, "showOutlines", true
      field :segments, "segments"
      field :value, "value", 0
      field :value_format, "valueFormat", "Percentage"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A grouped vertical bar chart.
    class GroupedVerticalBarChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.VerticalBar.Grouped"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :x_axis_title, "xAxisTitle"
      field :y_axis_title, "yAxisTitle"
      field :color, "color"
      field :stacked, "stacked", false
      field :data, "data"
      field :show_bar_values, "showBarValues", false
      field :y_min, "yMin"
      field :y_max, "yMax"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A horizontal bar chart.
    class HorizontalBarChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.HorizontalBar"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :x_axis_title, "xAxisTitle"
      field :y_axis_title, "yAxisTitle"
      field :color, "color"
      field :data, "data"
      field :display_mode, "displayMode", "AbsoluteWithAxis"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A standalone icon element. Icons can be picked from the vast [Adaptive Card icon catalog](https://adaptivecards.microsoft.com/?topic=icon-catalog).
    class Icon < CardElement
      field :key, "key"
      field :type, "type", "Icon"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :name, "name"
      field :size, "size", "Standard"
      field :style, "style", "Regular"
      field :color, "color", "Default"
      field :select_action, "selectAction"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # An inline icon inside a RichTextBlock element.
    class IconRun < CardElement
      field :key, "key"
      field :type, "type", "IconRun"
      field :id, "id"
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :is_sort_key, "isSortKey", false
      field :name, "name"
      field :size, "size", "Default"
      field :style, "style", "Regular"
      field :color, "color", "Default"
      field :select_action, "selectAction"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A standalone image element.
    class Image < CardElement
      field :key, "key"
      field :type, "type", "Image"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :url, "url"
      field :alt_text, "altText"
      field :background_color, "backgroundColor"
      field :style, "style", "Default"
      field :size, "size", "Auto"
      field :width, "width", "auto"
      field :select_action, "selectAction"
      field :allow_expand, "allowExpand", false
      field :msteams, "msteams"
      field :themed_urls, "themedUrls"
      field :fit_mode, "fitMode", "Fill"
      field :horizontal_content_alignment, "horizontalContentAlignment", "Left"
      field :vertical_content_alignment, "verticalContentAlignment", "Top"
      field :height, "height", "auto"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # An inline image inside a RichTextBlock element.
    class ImageRun < CardElement
      field :key, "key"
      field :type, "type", "ImageRun"
      field :id, "id"
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :is_sort_key, "isSortKey", false
      field :url, "url"
      field :size, "size", "Default"
      field :style, "style", "Default"
      field :select_action, "selectAction"
      field :themed_urls, "themedUrls"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A set of images, displayed side-by-side and wrapped across multiple rows as needed.
    class ImageSet < CardElement
      field :key, "key"
      field :type, "type", "ImageSet"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :images, "images"
      field :image_size, "imageSize", "Medium"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Inserts an image into the host application's canvas.
    class InsertImageAction < Action
      field :key, "key"
      field :type, "type", "Action.InsertImage"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :url, "url"
      field :alt_text, "altText"
      field :insert_position, "insertPosition", "Selection"
      field :fallback, "fallback"
    end

    # A line chart.
    class LineChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.Line"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :x_axis_title, "xAxisTitle"
      field :y_axis_title, "yAxisTitle"
      field :color, "color"
      field :data, "data"
      field :y_min, "yMin"
      field :y_max, "yMax"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A media element, that makes it possible to embed videos inside a card.
    class Media < CardElement
      field :key, "key"
      field :type, "type", "Media"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :sources, "sources"
      field :caption_sources, "captionSources"
      field :poster, "poster"
      field :alt_text, "altText"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # An input to allow the user to enter a number.
    class NumberInput < CardElement
      field :key, "key"
      field :type, "type", "Input.Number"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value"
      field :placeholder, "placeholder"
      field :min, "min"
      field :max, "max"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Opens the provided URL in either a separate browser tab or within the host application.
    class OpenUrlAction < Action
      field :key, "key"
      field :type, "type", "Action.OpenUrl"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :url, "url"
      field :fallback, "fallback"
      positional_field :url
    end

    # Opens a task module in a modal dialog hosting the content at a provided URL.
    class OpenUrlDialogAction < Action
      field :key, "key"
      field :type, "type", "Action.OpenUrlDialog"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :dialog_title, "dialogTitle"
      field :dialog_height, "dialogHeight"
      field :dialog_width, "dialogWidth"
      field :url, "url"
      field :fallback, "fallback"
    end

    # A pie chart.
    class PieChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.Pie"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :data, "data"
      field :value, "value"
      field :value_color, "valueColor"
      field :thickness, "thickness"
      field :show_outlines, "showOutlines", true
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Shows a popover to display more information to the user.
    class PopoverAction < Action
      field :key, "key"
      field :type, "type", "Action.Popover"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :themed_icon_urls, "themedIconUrls"
      field :content, "content"
      field :display_arrow, "displayArrow", true
      field :position, "position", "Above"
      field :max_popover_width, "maxPopoverWidth"
      field :fallback, "fallback"
    end

    # A progress bar element, to represent a value within a range.
    class ProgressBar < CardElement
      field :key, "key"
      field :type, "type", "ProgressBar"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :value, "value"
      field :max, "max", 100
      field :color, "color", "Accent"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A spinning ring element, to indicate progress.
    class ProgressRing < CardElement
      field :key, "key"
      field :type, "type", "ProgressRing"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :label_position, "labelPosition", "Below"
      field :size, "size", "Medium"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A read-only star rating element, to display the rating of something.
    class Rating < CardElement
      field :key, "key"
      field :type, "type", "Rating"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :value, "value"
      field :count, "count"
      field :max, "max", 5
      field :size, "size", "Large"
      field :color, "color", "Neutral"
      field :style, "style", "Default"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # An input to allow the user to rate something using stars.
    class RatingInput < CardElement
      field :key, "key"
      field :type, "type", "Input.Rating"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value"
      field :max, "max", 5
      field :allow_half_steps, "allowHalfSteps", false
      field :size, "size", "Large"
      field :color, "color", "Neutral"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Resets the values of the inputs in the card.
    class ResetInputsAction < Action
      field :key, "key"
      field :type, "type", "Action.ResetInputs"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :target_input_ids, "targetInputIds"
      field :fallback, "fallback"
    end

    # A rich text block that displays formatted text.
    class RichTextBlock < CardElement
      field :key, "key"
      field :type, "type", "RichTextBlock"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label_for, "labelFor"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :inlines, "inlines"
    end

    # Expands or collapses an embedded card within the main card.
    class ShowCardAction < Action
      field :key, "key"
      field :type, "type", "Action.ShowCard"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :fallback, "fallback"
      field :card, "card"
    end

    # A layout that stacks elements on top of each other. Layout.Stack is the default layout used by AdaptiveCard and all containers.
    class StackLayout < ContainerLayout
      field :key, "key"
      field :type, "type", "Layout.Stack"
      field :target_width, "targetWidth"
    end

    # A stacked horizontal bar chart.
    class StackedHorizontalBarChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.HorizontalBar.Stacked"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :x_axis_title, "xAxisTitle"
      field :y_axis_title, "yAxisTitle"
      field :color, "color"
      field :data, "data"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Gathers input values, merges them with the data property if specified, and sends them to the Bot via an Invoke activity. The Bot can only acknowledge is has received the request.
    class SubmitAction < Action
      field :key, "key"
      field :type, "type", "Action.Submit"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :data, "data"
      field :associated_inputs, "associatedInputs"
      field :conditionally_enabled, "conditionallyEnabled", false
      field :msteams, "msteams"
      field :fallback, "fallback"
    end

    # Use tables to display data in a tabular way, with rows, columns and cells.
    class Table < CardElement
      field :key, "key"
      field :type, "type", "Table"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :style, "style"
      field :show_border, "showBorder", false
      field :rounded_corners, "roundedCorners", false
      field :columns, "columns"
      field :min_width, "minWidth"
      field :first_row_as_headers, "firstRowAsHeaders", true
      field :show_grid_lines, "showGridLines", true
      field :grid_style, "gridStyle"
      field :horizontal_cell_content_alignment, "horizontalCellContentAlignment"
      field :vertical_cell_content_alignment, "verticalCellContentAlignment"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :rows, "rows"
    end

    # Represents a cell in a table row.
    class TableCell < CardElement
      field :key, "key"
      field :type, "type", "TableCell"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :select_action, "selectAction"
      field :style, "style"
      field :layouts, "layouts"
      field :bleed, "bleed", false
      field :min_height, "minHeight"
      field :background_image, "backgroundImage"
      field :vertical_content_alignment, "verticalContentAlignment"
      field :rtl, "rtl"
      field :max_height, "maxHeight"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :items, "items"
    end

    # Represents a row of cells in a table.
    class TableRow < CardElement
      field :key, "key"
      field :type, "type", "TableRow"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :show_border, "showBorder", false
      field :rounded_corners, "roundedCorners", false
      field :style, "style"
      field :horizontal_cell_content_alignment, "horizontalCellContentAlignment"
      field :vertical_cell_content_alignment, "verticalCellContentAlignment"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      field :cells, "cells"
    end

    # A block of text, optionally formatted using Markdown.
    class TextBlock < CardElement
      field :key, "key"
      field :type, "type", "TextBlock"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :text, "text"
      field :size, "size"
      field :weight, "weight"
      field :color, "color"
      field :is_subtle, "isSubtle"
      field :font_type, "fontType"
      field :wrap, "wrap", false
      field :max_lines, "maxLines"
      field :style, "style"
      field :label_for, "labelFor"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
      positional_field :text
    end

    # An input to allow the user to enter text.
    class TextInput < CardElement
      field :key, "key"
      field :type, "type", "Input.Text"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value"
      field :max_length, "maxLength"
      field :is_multiline, "isMultiline", false
      field :placeholder, "placeholder"
      field :style, "style", "Text"
      field :inline_action, "inlineAction"
      field :regex, "regex"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # A block of text inside a RichTextBlock element.
    class TextRun < CardElement
      field :key, "key"
      field :type, "type", "TextRun"
      field :id, "id"
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :is_sort_key, "isSortKey", false
      field :text, "text"
      field :size, "size"
      field :weight, "weight"
      field :color, "color"
      field :is_subtle, "isSubtle"
      field :font_type, "fontType"
      field :italic, "italic", false
      field :strikethrough, "strikethrough", false
      field :highlight, "highlight", false
      field :underline, "underline", false
      field :select_action, "selectAction"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # An input to allow the user to select a time.
    class TimeInput < CardElement
      field :key, "key"
      field :type, "type", "Input.Time"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value"
      field :placeholder, "placeholder"
      field :min, "min"
      field :max, "max"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # An input to allow the user to select between on/off states.
    class ToggleInput < CardElement
      field :key, "key"
      field :type, "type", "Input.Toggle"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :label, "label"
      field :is_required, "isRequired", false
      field :error_message, "errorMessage"
      field :value_changed_action, "valueChangedAction"
      field :value, "value", "false"
      field :title, "title"
      field :value_on, "valueOn", "true"
      field :value_off, "valueOff", "false"
      field :wrap, "wrap", true
      field :show_title, "showTitle", true
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end

    # Toggles the visibility of a set of elements. Action.ToggleVisibility is useful for creating "Show more" type UI patterns.
    class ToggleVisibilityAction < Action
      field :key, "key"
      field :type, "type", "Action.ToggleVisibility"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :title, "title"
      field :icon_url, "iconUrl"
      field :style, "style", "default"
      field :mode, "mode", "primary"
      field :tooltip, "tooltip"
      field :is_enabled, "isEnabled", true
      field :menu_actions, "menuActions"
      field :themed_icon_urls, "themedIconUrls"
      field :target_elements, "targetElements"
      field :fallback, "fallback"
    end

    # A vertical bar chart.
    class VerticalBarChart < CardElement
      field :key, "key"
      field :type, "type", "Chart.VerticalBar"
      field :id, "id"
      field :requires, "requires", {}, mutable: true
      field :lang, "lang"
      field :is_visible, "isVisible", true
      field :separator, "separator", false
      field :height, "height", "auto"
      field :horizontal_alignment, "horizontalAlignment"
      field :spacing, "spacing", "Default"
      field :target_width, "targetWidth"
      field :is_sort_key, "isSortKey", false
      field :title, "title"
      field :show_title, "showTitle", false
      field :color_set, "colorSet"
      field :max_width, "maxWidth"
      field :show_legend, "showLegend", true
      field :x_axis_title, "xAxisTitle"
      field :y_axis_title, "yAxisTitle"
      field :data, "data"
      field :color, "color"
      field :show_bar_values, "showBarValues", false
      field :y_min, "yMin"
      field :y_max, "yMax"
      field :grid_area, "gridArea"
      field :fallback, "fallback"
    end
  end
end
